server.name: kibana
server.host: "20.0.0.10"
elasticsearch.hosts: [ "http://20.0.0.9:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: iYU2RF{yT&&-]8D:ew#;b!*6/8=2q:Px